### ISSUE TITLE
Code duplication in protocol files

### ISSUE THREAD

**Issue by Fristi** [Blizzard/heroprotocol#10]
Each protocol has methods like `_decode_event_stream`, but they all seem to be the same at first sight. Are the subtle differences? Could these duplicate methods be refactored to generic methods?

**Comment by cherstewart** [comment]
Run a diff on them, I haven't had time to look at them much

On Sun, Jan 31, 2016 at 3:00 AM, Mark <notifications@github.com> wrote:

> Each protocol has methods like _decode_event_stream, but they all seem to
> be the same at first sight Are the subtle differences? Could these
> duplicate methods be removed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blizzard/heroprotocol/issues/10>.
>



-- 
Cher Stewart

You cannot do all the good the world needs, but the world needs all the
good you can do.

**Comment by jnovack** [comment]
Everything below `tracker_event_types` is exactly across all files.

Could be better served as a class.

**Comment by cherstewart** [comment]
My fork is markedly different than the master branch now, but I can look at
it later today to make another fork to fix it

On Sun, Jan 31, 2016 at 8:34 AM, Justin J. Novack <notifications@github.com>
wrote:

> Everything below tracker_event_types is exactly across all files.
>
> Could be better served as a class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blizzard/heroprotocol/issues/10#issuecomment-177545165>
> .
>



-- 
Cher Stewart

You cannot do all the good the world needs, but the world needs all the
good you can do.

**Comment by Regner** [comment]
I have actually already done this on my fork. You can see it in the branch "improve_api" here: https://github.com/Regner/heroprotocol/blob/improve_api/heroprotocol/heroprotocol.py

I moved all of the functions from the protocol files into my HeroProtocol class.

Next on my list is trying to source a replay file for every version that this library is supposed to support so I can run tests against them to make sure it always works at least without raising an exception.

**Comment by jnovack** [comment]
I don't mind sharing my awful replays.  I've been playing (consistently, in terms of time, not skill level) since early alpha and have many versions.

**Comment by Regner** [comment]
@jnovack Here are the ones I have: https://github.com/Regner/heroprotocol/tree/adding_tests/tests/replays

Any missing ones you can supply would be greatly appreciated. :)

**Comment by Fristi** [comment]
Moving these methods would be this would be nice :+1:  Questioning though why these methods were there in the first place. HotS is based on SC2, which also has a similar replay structure which might be the reason for having these methods in the first place?

I can also provide some old replays, but have to sort them. 

I am the early stages of creating a Scala version of replaying HotS files. Currently parsing all python protocol files and converting python AST to scodec' codecs to extract data from the mpq/replay files. This seems not really straight forward, but I would like to treat these protocol files as some sort of DSL which describes the protocol format. I've done some experiments with sending data via JSON to a scala app, but this doesn't scala very well (separate python processes, not really resilient etc)

**Comment by cherstewart** [comment]
Ah, now we've both done it!

On Mon, Feb 1, 2016 at 1:03 AM, Regner Blok-Andersen <
notifications@github.com> wrote:

> I have actually already done this on my fork. You can see it in the branch
> "improve_api" here:
> https://github.com/Regner/heroprotocol/blob/improve_api/heroprotocol/heroprotocol.py
>
> I moved all of the functions from the protocol files into my HeroProtocol
> class.
>
> Next on my list is trying to source a replay file for every version that
> this library is supposed to support so I can run tests against them to make
> sure it always works at least without raising an exception.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blizzard/heroprotocol/issues/10#issuecomment-177862717>
> .
>



-- 
Cher Stewart

You cannot do all the good the world needs, but the world needs all the
good you can do.

**Comment by Regner** [comment]
Hehehe! Care to push your changes to your repo @cherstewart? Would love to see how you did it.

**Comment by jnovack** [comment]
@Regner I uploaded (all my unique protocol versions)[https://github.com/jnovack/heroes-replays] with the output from Blizzard's `heroprotocol.py` so that you can verify against your refactoring.

I've tried to include as little files as possible with messages (I do not want to witch-hunt anyone), and the four files that have messages are innocuous.

**Comment by Regner** [comment]
Thank you very much! I didn't even check mine. I should probably write a script to source the shortest ones possible since that makes the tests run faster. I would hate if they somehow started a which hunt. :(
