### ISSUE TITLE
missing protocols 33182, 33353, 33684

### ISSUE THREAD

**Issue by jnovack** [Blizzard/heroprotocol#11]
The following protocols are missing:

* 33182
* 33353
* 33684

**Comment by jnovack** [comment]
They are clearly different from 32524 and 34053, as I've tried [bolth](https://www.youtube.com/watch?v=tlmf1kQL-to).

**Comment by tenarsis** [comment]
Uploaded these too, thanks!

**Comment by jnovack** [comment]
How many more do you have back there? :)

**Comment by tenarsis** [comment]
All protocol files for released builds should be up now :) Let me know if you still find more missing.
