### ISSUE TITLE
Missing protocol39595

### ISSUE THREAD

**Issue by Regner** [Blizzard/heroprotocol#15]
Have a replay with m_baseBuild 39595

**Comment by jnovack** [comment]
You mean this file?  https://github.com/Blizzard/heroprotocol/blob/master/protocol39595.py

**Comment by Regner** [comment]
Huh, yea. I merged this repo into mine but didn't seem to get that file. Will try again. Sorry!

**Comment by jnovack** [comment]
Don't feel bad, I PR'd it last night. :)

https://github.com/Blizzard/heroprotocol/commit/77df8913d4933cc1a911f214024054778b13b5ec
