### ISSUE TITLE
to few argument

### ISSUE THREAD

**Issue by straziboy** [Blizzard/heroprotocol#19]
hi 

i'm a beginner in python and i try to use the first example but it didn't work
i have a error 

heroprotocol.py to few arguments

i have just replace the name of my replay file in the command like this

py heroprotocol.py --details "test.StormReplay" > output.txt

someone can explain me what is my mystake please

Thank you

Straziboy

**Comment by crorella** [comment]
I'm not sure what's wrong. I tried the same command and I see output. Is the replay in the same folder as heroprotocol.py?

**Comment by straziboy** [comment]
i have the solution 

in my computer the the command isn't

py heroprotocol.py --details "test.StormReplay" > output.txt

but

python heroprotocol.py --details "test.StormReplay" > output.txt

i don't understand why now it works

thanks for you replies

**Comment by cazrin** [comment]
It would have depended whether `py` is in your path and/or aliased to `python`. We can close this issue now @straziboy
