### ISSUE TITLE
Hero Ban Information

### ISSUE THREAD

**Issue by barrett777** [Blizzard/heroprotocol#32]
Hello!

In the new PTR replay protocol, I haven't been able to find ban information.

Is this available in the replay file?

If not, would you be able to add it to 'replay.attribute.events', since there is other related draft info?

**Comment by tenarsis** [comment]
While not exposed by the replay parser, the data should already be in the replay.server.battlelobby file.

Long term, it'd be good to get it into one of the files that can be parsed in a convenient format.

**Comment by barrett777** [comment]
Can you give any guidance as to how to parse the replay.server.battlelobby file? :)

**Comment by tenarsis** [comment]
Easier to just add the data into replay.attribute.events. Sorry I can't give a timeline on that but we know that exposing draft data into the replay is a top request.

**Comment by jnovack** [comment]
I love that answer.

"It's over there."
"Can you tell me how to get there?"
"Meh, it's easier if we move it."

:)

**Comment by jnovack** [comment]
To be honest, the draft information is interesting to others as well.  Who was banned first, picked second, and how much time they took (if you save that).

Sad that we won't get `replay.server.battlelobby`, but we understand if something is hidden in there. :/

**Comment by cazrin** [comment]
The only thing I've managed to find in `replay.server.battlelobby` is the Battle.net IDs of each player (including the `#1234` after the name). Would like to have more coverage in the library as well if possible, but understand it probably isn't a priority.

**Comment by barrett777** [comment]
Correct me if I'm wrong, but it looks like you have added this to 'replay.attribute.events' after all!

I'll more verifying today but I've checked two replays so far and it matches up:

{Player: 16, AttributeType: 4021, Value: **Mban**}	 -> Mid Ban?
{Player: 16, AttributeType: 4022, Value: **Hmmr**} -> Perhaps identifying the highest MMR player chooses the bans?
{Player: 16, AttributeType: 4023, Value: **Wiza**}	Team 1 First Ban
{Player: 16, AttributeType: 4024, Value: 	
{Player: 16, AttributeType: 4025, Value: **Illi**} Team 1 Second Ban (I hate Illidan)
{Player: 16, AttributeType: 4026, Value: 	
{Player: 16, AttributeType: 4027, Value: **Hmmr**}	
{Player: 16, AttributeType: 4028, Value: **Tych**}	Team 2 First Ban
{Player: 16, AttributeType: 4029, Value: 	
{Player: 16, AttributeType: 4030, Value: **Medi**}	Team 2 Second Ban
{Player: 16, AttributeType: 4031, Value: 	

I'll close this issue since it looks pretty complete :) If I find any problems I'll comment here later

**Comment by tenarsis** [comment]
Nice!

Here's the names for those attribute ids, in case that helps clarify:
DRAFT_BAN_MODE = 4021,
DRAFT_TEAM1_BAN_CHOOSER_SLOT = 4022,
DRAFT_TEAM1_BAN1 = 4023,
DRAFT_TEAM1_BAN1_LOCKED_IN = 4024,
DRAFT_TEAM1_BAN2 = 4025,
DRAFT_TEAM1_BAN2_LOCKED_IN = 4026,
DRAFT_TEAM2_BAN_CHOOSER_SLOT = 4027,
DRAFT_TEAM2_BAN1 = 4028,
DRAFT_TEAM2_BAN1_LOCKED_IN = 4029,
DRAFT_TEAM2_BAN2 = 4030,
DRAFT_TEAM2_BAN2_LOCKED_IN = 4031,

And the values:
DraftBanLockedIn_Yes("yes");
DraftBanLockedIn_No("no");
DraftBanMode_NoBan("");
DraftBanMode_OneBan("1ban");
DraftBanMode_TwoBan("2ban");
DraftBanMode_MidBan("Mban");
DraftBanChooser_HighestMMR("Hmmr");

**Comment by barrett777** [comment]
Perfect! :)

**Comment by jnovack** [comment]
Can you confirm?

Locked In "Yes" - Ban selected and locked in.
Locked In "No" - Ban selected, but let timer expire.
4023/4025/4028/4030 empty = Ban not selected, timer expired.

**Comment by barrett777** [comment]
The 'Locked In' values have been empty for me for all the replays I've looked at, though this isn't really needed

If a ban isn't selected, the value such as DRAFT_TEAM2_BAN1 will be an empty string

**Comment by TheUberKid** [comment]
So the attribute events only output the first 4 characters of each hero's name, which becomes a problem if you're trying to figure out who was banned here:

{Player: 16, AttributeType: 4023, Value: Medi}

Both Lt. Morales (medic) and Medivh (medivh) start with `medi` and they appear as the same in the replay bans. Is there a way to tell the difference?

**Comment by barrett777** [comment]
Here's a list of the current 4 character names: https://apiapp.hotslogs.com/API/Data/Heroes

Medivh = Mdvh
Lt. Morales = Medi
