### ISSUE TITLE
'ScoreResultEvent' has wrong player indexes sometimes in multiple observer scenarios

### ISSUE THREAD

**Issue by barrett777** [Blizzard/heroprotocol#33]
I'm trying to parse the 'Round of 8' replays from 'Heroes of the Dorm 2016', which are publicly available: https://compete.tespa.org/tournament/19/phase/1

So far in this tournament I've been able to parse most of them fine.  However, in 'Round of 8', I've only been able to successfully line up the 'ScoreResultEvent' player indexes with the 'ClientList' 2/10 times.

I'm not sure why this happens, but it seems to be related to many observers.

For example, in the one replay I'm looking at, I see Observers in ClientList slots 0,1,2,3,4, and players in ClientList slots 5,6,7,8,9,10,11,12,13,14.  However, in the 'ScoreResultEvent', stats are being recorded for ClientList slots 6-15.  There isn't a player in ClientList slot 15.

The first 'PlayerSetup' tracker events also show each player with a client list index from 5-14.  It seems to only be the 'ScoreResultEvent' that is showing the 6-15.

[19100-5777-2-Anaklu.zip](https://github.com/Blizzard/heroprotocol/files/191363/19100-5777-2-Anaklu.zip)

**Comment by barrett777** [comment]
So I found my confusion, and perhaps you can clarify:

I thought there was only one 'ClientList', which is from the replay.initData file here:

('_struct',[[('**m_userInitialData**',48,-3),('m_gameDescription',58,-2),('m_lobbyState',67,-1)]]),  #68

'm_userInitialData' lists all observers and players.  The 'm_userId' in replay.game.events uses this 'ClientList' order, and so do the 'replay.attribute.events.'

The only place I've found to use a different 'ClientList' is this new 'ScoreResultEvent', which looks like it is using 'm_workingSetSlotId' from 'replay.details.'

Is 'm_workingSetSlotId' used anywhere else?  What is the difference between 'm_workingSetSlotId' and 'm_userId'?

**Comment by tenarsis** [comment]
Sorry this wasn't documented anywhere. m_workingSetSlotId has the correct index into the ScoreResultEvent for each user. There's no reason that ScoreResultEvent couldn't instead be indexed on m_userId but it's too late to change it now without breaking compatibility.
