### ISSUE TITLE
Experience discrepancies between SScoreResultEvent and SStatGameEvent

### ISSUE THREAD

**Issue by crorella** [Blizzard/heroprotocol#34]
Hi,

I was checking some replays and noted the total amount of experience earned by a team at the end of the game, as reported by SScoreResultEvent in the MetaExperience field is different than the sum of HeroXP + TrickleXP + StructureXP + CreepXP + MinionXP reported in SStatGameEvent in the field EndOfGameXPBreakdown.

Also, if you sum the  ExperienceContribution (reported in SScoreResultEvent) for each hero of each team you will get a third value for what is supposed to be the total amount of experience earned by a team.

Summarizing, if you sum the XP contribution by hero you will get a different value if you sum the XP contribution by XP Type which is also different as the MetaExperience.

Do you know how should we interpret the values so they match?

**Comment by barrett777** [comment]
Are you dividing 'MetaExperience' by 4096 like the other 'SScoreResultEvent' entries?

**Comment by crorella** [comment]
Hi @barrett777, yes I'm doing it.

I noted 'PeriodicXPBreakdown' + EndOfGameXPBreakdown = MetaExperience
Now the only missing piece is to understand why the sum of each individual ExperienceContribution is different than MetaExperience for each team.

**Comment by barrett777** [comment]
I don't think you add 'PeriodicXPBreakdown' and 'EndOfGameXPBreakdown' together, I think they are the same thing, just at different points in time during the game.

'PeriodicXPBreakdown' isn't showing a difference in XP from the previous event, it's showing all XP gathered at that point.

In a game I just looked at, the last 'PeriodicXPBreakdown' happened at 22:38, and the sum of one team was 110896 XP.

The game ended at 23:01, and in the 'ScoreResult', the same team's 'MetaExperience' is 111976.  The difference here probably being the time between 22:38 and 23:01.

**Comment by crorella** [comment]
Yes you are right, you don't add them, what I wanted to say is EndOfGameXPBreakdown is the last datapoint of EndOfGameXPBreakdown

**Comment by barrett777** [comment]
It looks like the 'EndOfGameXPBreakdown' does add up to exactly equal the same team's 'MetaExperience'

One misleading piece is that each player shares the same XP.  The 'EndOfGameXPBreakdown' has a record for each player, but this is actually a sum of the team's XP - each player on a team will have the same values.

If you add up 'CreepXP', 'HeroXP', 'MinionXP', 'StructureXP', and 'TrickleXP' for a player in the 'EndOfGameXPBreakdown', it should exactly match the 'MetaExperience' for that player as well
