### ISSUE TITLE
Add support for protocol 42958

### ISSUE THREAD

**Issue by crorella** [Blizzard/heroprotocol#35]
Hello,

it's not possible to decode the game events from the newest replay version, the error:

```
Traceback (most recent call last):
  File "heroprotocol.py", line 112, in <module>
    for event in protocol.decode_replay_game_events(contents):
  File "/Users/cristiano/Others/hots-parser/heroprotocol/protocol42958.py", line 412, in decode_replay_game_events
    decode_user_id=True):
  File "/Users/cristiano/Others/hots-parser/heroprotocol/protocol42958.py", line 385, in _decode_event_stream
    raise CorruptedError('eventid(%d) at %s' % (eventid, decoder))
CorruptedError: eventid(0) at buffer(00/4,[3918]=04)
```

**Comment by barrett777** [comment]
I'm sure they'll add an official one soon, they usually do same day a new patch comes out

For now, the only difference I've found so far is 'm_cmdFlags' is 24 bits instead of 25 in the previous protocol.  This is the first field in the 'SCmdEvent' definition

**Comment by crorella** [comment]
Thanks for the info @barrett777. I was hoping to see some indicator of how the player completed the quest talents, something like "8/25 stacks" or something like that 😄

**Comment by tenarsis** [comment]
Sorry for the delay. Trying to see what we can do to make sure they're uploaded sooner in the future.
