### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by regner** [Blizzard/heroprotocol#4]
The package is missing a setup.py along with the following:
- mpyq should be removed from this repo
- a requirements.txt should be added and included in the setup.py install requirements
- a travis ci build should be setup, even with no tests the travis CI can take care of releasing to pypi

1 and 2 should be doable in a single PR but 3 should probably be done in another repo and by someone at Blizzard.

**Comment by gdraynz** [comment]
1 and 2 should definitely be done! One repository per package is the way to go :)
One can always clone `mypq` separately and use its code locally if he needs to.

**Comment by Regner** [comment]
Every thing seems to work just requiring ```mpyq==0.2.0```. That is the version number in the included version of mpyq so the one I set in the requirements.

**Comment by Agilhardt** [comment]
heroprotocol is now available at PyPI: https://pypi.org/project/heroprotocol/
The next update to master will include setup.py and other changes related to this.
