### ISSUE TITLE
Get game length in seconds?

### ISSUE THREAD

**Issue by brhs** [Blizzard/heroprotocol#46]
Are game loops (`elapsedGameLoops`) the same thing as seconds, and if not, how many loops are in a second?

**Comment by barrett777** [comment]
The HotS engine runs at a set 16 game loops per second, so divide 'elapsedGameLoops' by 16 to get total seconds

**Comment by brhs** [comment]
Thanks!

Wait, are you the hotslogs guy?

**Comment by barrett777** [comment]
Indeed! :)
