### ISSUE TITLE
Translating between camera and map coordinates?

### ISSUE THREAD

**Issue by bchbchbch** [Blizzard/heroprotocol#47]

**Comment by brhs** [comment]
sc2reader [divides by 4096](https://github.com/GraylinKim/sc2reader/blob/master/sc2reader/events/game.py#L265-L269). I tried that and the numbers are in the right ballpark. Going to assume that's the answer.

Does anyone know why 4096, and how that number was discovered?

**Comment by RodrigoPetter** [comment]
I found this: https://github.com/Farof/heroprotocoljs/blob/master/reference/replay.tracker.events.md#nnetreplaytrackersplayerstatsevent
> In NNet.Replay.Tracker.SPlayerStatsEvent, m_scoreValueFoodUsed and m_scoreValueFoodMade are in fixed point (divide by 4096 for integer values). All other values are in integers.

And complementing: https://en.wikipedia.org/wiki/Fixed-point_arithmetic
