### ISSUE TITLE
What is a player's toon and id?

### ISSUE THREAD

**Issue by TheUberKid** [Blizzard/heroprotocol#48]
A `m_toon` object for each player can be found in `details.m_playerList`. Inside this object is a value called `m_id` that seems to be a unique number for each player, consistent for the same player across different replays.

At first thought, I assumed it could be the BattleTag of a player, but the two did not match. What is a player's Toon Id, and what is it used for? In addition, is there any way of finding the BattleTags of players in the replay file?

**Comment by koliva8245** [comment]
A toon is  `{m_region}-Hero-{m_realm}-{m_id}`, for example 1-Hero-1-234234. 
I guess the toon can be used to identify the player.

The BattleTags can be found in the `replay.server.battlelobby` file.

**Comment by TheUberKid** [comment]
Okay, thanks.
