### ISSUE TITLE
Why double or triple the replay file size for the single new event  'NNet.Game.STriggerMouseMovedEvent'?

### ISSUE THREAD

**Issue by ghost** [Blizzard/heroprotocol#50]
Is there a good reason to include this in StormReplay files when it causes them to grow in size by 2-3 times?  (there are about 200,000 such events in the game.events file I just looked at).  Ignoring the effect on developers trying to still get replay files, this will for sure cause many more users to delete their old replay files.

**Comment by crorella** [comment]
I think this happens when you keep pressed the mouse button (secondary button)

**Comment by zxqfox** [comment]
With gzip this should not be a big problem. Prob we can just gzip 'em all!

**Comment by myrddraall** [comment]
because the engine needs those events to reconstruct the game state, Without them the game would have no idea where you where aiming when you fired a skill.

**Comment by barrett777** [comment]
@myrddraall This is a newer event type, which is why there's concern.  This event wasn't needed by the game engine for a long time.

**Comment by myrddraall** [comment]
Ah ok, i think I've confused it with the click/command events

**Comment by tenarsis** [comment]
We fixed this ;) Thanks for the report.

https://heroesofthestorm.com/en-us/blog/22012454/heroes-of-the-storm-patch-notes-august-7-2018-2018-8-7/
* Reduced the size of replay files.
