### ISSUE TITLE
Parsing unit/hero movements

### ISSUE THREAD

**Issue by alexisabril** [Blizzard/heroprotocol#52]
Apologies if this is not the correct forum. Is it possible to derive unit/hero movements from the parsed replay data? From the gameevents report, I do see events such as:

```
{
	"_eventid": 8,
	"_event": "NNet.Replay.Tracker.SUnitPositionsEvent",
	"_bits": 1800,
	"m_items": [0, 133, 125, 7, 104, ..., N],
	"m_firstUnitIndex": 1,
	"_gameloop": 13440
}
```

In other events, such as UnitBorn, I do see coordinate `m_x/m_y` properties.

Is it possible to derive the movement and/or path of a unit from the parsed replay data?

**Comment by barrett777** [comment]
Yes you can derive unit movements! And I already do :)

Though my replay parser is in C#.  The event you are describing is from Blizzard's python one: https://github.com/Blizzard/heroprotocol

I can't offer support for the python one

For mine, after parsing, you get a Replay object. That has an array of Units, and each Unit has Positions with timestamps

**Comment by alexisabril** [comment]
Thank you for the response @barrett777! I'm closing this as a non-issue for this project. However, if not too intrusive, I'll post any additional questions in your project.
