### ISSUE TITLE
Documentation for event names?

### ISSUE THREAD

**Issue by Onoam** [Blizzard/heroprotocol#54]
Hello,
I am trying to find documentation or some sort of explanation for the items in the output.
For example, I was not sure whether in --details, under m_playerList, m_result "1" means defeat and "2" means victory or the other way around. Many things are self-explanatory but some of the dictionaries (many of the things starting with "m_") are not...

As may be clear, I don't have an understanding of JSON formats and I just basically dumped it into a Pandas dataframe with pd.read_json, so forgive me if I am missing something blatantly obvious :)

Thanks in advance!

**Comment by mikeeheler** [comment]
Nothing official right now. The heroprotocol project is pretty much a raw dump of the data structures and the rest has been filled in by enterprising members of the community. There's a community-made protocol doc at https://nexus-devtools.github.io/heroprotocoldocs/#/ as referenced in #57. It's a work in progress but provides a nice tool with the Playground to explore and experiment with the data.
