### ISSUE TITLE
how to convert 18 digit timestamp?

### ISSUE THREAD

**Issue by junkwhinger** [Blizzard/heroprotocol#56]
Hi, using heroprotocol.py --detail I managed to parse my playlogs, but can't seem to parse timestamp correctly. For example the one i have is data['m_timeUTC'] = '131485808427443680'. On the replay section in the game it seems its '2017-04-17'. I'd appreciate if someone could tell me how to parse this in python. Thanks!

**Comment by barrett777** [comment]
This is Windows filetime, which I believe is ticks since 1970.  You can search online for windows filetime converters

**Comment by junkwhinger** [comment]
Thanks it works! :)
here's my python code to convert Windows filetime to python datetime object.
`ts = datetime.datetime.fromtimestamp((data['m_timeUTC'] - 116444736000000000) // 10000000)`

**Comment by mehdi-kaytoue** [comment]
Very helpful @junkwhinger $, thank you!
