### ISSUE TITLE
Add an API that wraps MPQArchive and protocol methods

### ISSUE THREAD

**Issue by regner** [Blizzard/heroprotocol#6]
As a developer working in python I should be able to import an object which I can initialize with the path to a .StormReplay file. After which I have access to all of the `decode_replay_*` method directly on the object.

**Comment by Regner** [comment]
If PR #5 is accepted I started some work over on my fork in another branch. You can see the beginnings of it here: https://github.com/Regner/heroprotocol/blob/improve_api/heroprotocol/heroprotocol.py

Totally open to some suggestions.
