### ISSUE TITLE
Commit signature verification

### ISSUE THREAD

**Issue by ajbdev** [Blizzard/heroprotocol#61]
I have a project that I am working on that will be automatically downloading from this project and performing some conversion to the source files. I know there are other projects out there such as [heroprotocoljs](https://github.com/nydus/heroprotocol) that are also doing something similar. 

Is there a way these automated protocol uploads could be GPG signed to help ensure authenticity?

**Comment by naomichan** [comment]
> nydus/heroprotocol
It just dawned on me that I probably should've gave a better name for my [automated JS port of heroprotocol...](https://github.com/naomichan/nydus)

> Is there a way these automated protocol uploads could be GPG signed to help ensure authenticity?

Specifically signing the commits since that's now part of git.

**Comment by Agilhardt** [comment]
Hey guys, sorry for the late response on this. Anyway, I am going to be better about communicating on this repo.

I think this is a great idea. I'm very much an advocate of GPG encryption and signing, however signing commits is complicated by our auto publish pipeline, requiring someone to manually input a password. There are ways around it but it's more work than we can prioritize at the moment. I could sign the commits manually post-deploy, but would change the hash of the commit requiring a force push and a rebase by anyone synching the repo.. so I don't think we should do that.

What I could do is manually push signed tags for each release as a first step. Would that be helpful?

For the record I have generated a GPG key and published it to public keyservers. The fingerprint is [3AAD 6DB5 B2A8 0269 B254  F1BD 16F4 6930 1943 4EF5](https://pgp.mit.edu/pks/lookup?op=get&search=0x16F4693019434EF5).

**Comment by healingbrew** [comment]
You can set your gpg-agent in batch mode (`--batch --passphrase PASSWD`) if you run it as a daemon, though I don't know if this applies to WinGpg or not. It's a bit tricky to make Git listen to those commands though. It involves setting default GPG vars (`~/.gnupg` or `./gpg.conf`) but that has security risks.

**Comment by Agilhardt** [comment]
Yeah that's part of the "There are ways around it but..." bit, :-)

I will be investigating some other options. In the meantime, would signed tags (i.e. `tags/v2.34.3.66182 -> e663a6186ee8a80d089b9b5f78ca4650d78736e9`) work as a stop-gap or would they just clutter the ref space?

**Comment by Agilhardt** [comment]
All commits to this repo going forward will be signed / verified. Thanks for your patience.
