### ISSUE TITLE
Unsupported base build: 59799

### ISSUE THREAD

**Issue by poma** [Blizzard/heroprotocol#62]
Current hotfix on live is unsupported. I was assuming that changes are automatically pushed to this repo on client release, how come that this time it wasn't updated?

**Comment by poma** [comment]
so changes are pushed now but looks like new parser versions may come later that actual client updates. It is possible to push them sooner?

**Comment by tenarsis** [comment]
Normally it goes live along with the first region to patch. If there is ever a delay feel free to open an issue just like this, they are helpful indeed. Thanks!
