### ISSUE TITLE
DamageTaken vs DamageSoaked

### ISSUE THREAD

**Issue by myrddraall** [Blizzard/heroprotocol#70]
What is the difference? DamageSoaked  is usually  lower, but sometimes the same as damage taken.

**Comment by healingbrew** [comment]
If I were to guess, I'd say that soaked is restricted to heoric sources.

**Comment by myrddraall** [comment]
Yeah that was my guess too, but I'm finding quite a few games where players have identical numbers and i'm not sure i believe that they never once took damage from anything but heroes, Its possible but introduces doubt

**Comment by mikeeheler** [comment]
Heya @myrddraall, DamageSoaked is just DamageTaken minus a death penalty.

Each time a hero takes damage, the damage is added to both stats. When that hero dies, their max health pool at the time of death is subtracted.

If the hero didn't die that game, the stats will be identical.
