### ISSUE TITLE
Unsupported base build: 62424

### ISSUE THREAD

**Issue by casualMLG** [Blizzard/heroprotocol#73]
Hi!
I'm quite the newbie at python. SO I can't get heroprotocol working. I used the example command, provided the path to python 2.7 but all I get is "Unsupported base build: 62424"

**Comment by MGatner** [comment]
That's typically the error message you'd get when a replay can't match its build number to a corresponding protocol. Make sure you have the repo cloned/downloaded in its entirety and outside of any archives or compressed folders.

**Comment by casualMLG** [comment]
Thank you MGantner, I got it working now :)
I downloaded the zip file again and for some reason last time I only got some of the protocols.
I had only up to 57286.
Gonna close the issue now.
