### ISSUE TITLE
Can't find acount levels and played hero levels

### ISSUE THREAD

**Issue by casualMLG** [Blizzard/heroprotocol#74]
It would help a lot if anyone can help me locate these values. I assumed these would be in replay.details or replay.initData but I couldn't find them in any of the files. Are some values encoded even after decoding the files? for example in initdata the value of ['m_syncLobbyState']['m_lobbyState']['m_slots'][0]['m_heroMasteryTiers'][0][m_hero] is '@\x98\\\x9a' or similar which is gibberish to me :(

**Comment by koliva8245** [comment]
Hero levels are in `replay.attributes.events`, with the attribute being 4008.  Here it is in [Heroes.ReplayParser](https://github.com/barrett777/Heroes.ReplayParser/blob/fece8c73fbc4c697b6d5e6143c207b4120b6dd2a/Heroes.ReplayParser/MPQFiles/ReplayAttributeEvents.cs#L208-L220).

Account levels are found in `replay.server.battlelobby`. Its the 4 bytes after a player's battletag.

**Comment by casualMLG** [comment]
than you koliva8245
I'm using this heroprotocol project as a library to pick some values out of the replays. But I'm a beginner and I just figured out how to use it in python. returning those hero levels will be easy now but this project doesn't seem to touch the replay.server.battlelobby file at all. when I used mpyq.py to extract all files, this wasn't one of them either. I planned to use something like the following method to get the values:

from mpyq import mpyq
import protocol29406
archive = mpyq.MPQArchive("Blackheart's Bay.StormReplay")
header = protocol29406.decode_replay_header(archive.header['user_data_header']['content'])
baseBuild = header['m_version']['m_baseBuild']
protocol = __import__('protocol%s' % (baseBuild,))
details = protocol.decode_replay_details(archive.read_file('replay.details'))
for p in details['m_playerList']:
    print(p['m_name'] + ' played ' + p['m_hero'])

Unfortunately I have no idea how to get account levels from replay.server.battlelobby nor how to decode or even extract the file.

**Comment by MGatner** [comment]
Decoding the file is a much bigger issue, but koliva has pointed you to some resources for it. Extracting it is easier: heroprotocol comes with an old version of MPYQ that chokes on empty files, and there are a few before replay.server.battlelobby. Go get a copy of MPYQ from its own repo and use that to extract the same way - you’ll get all the files.

**Comment by casualMLG** [comment]
Seems like I don't need a different mpyq after all. There is a function to extract and read specific file. so this worked:
archive = mpyq.MPQArchive("Blackheart's Bay.StormReplay")
archive.extract_files('replay.server.battlelobby') 
Barret777's project is in C# and I don't know that language. Perhaps I could learn something from it still. Or from this python project [https://github.com/hotsdata/hots-parser](https://github.com/hotsdata/hots-parserl) and integrate it into my code.
Would it be possible to get a few values from the file without decoding it though?

**Comment by casualMLG** [comment]
thanks for the help hints everybody. I figured out how to get player account levels from replay.server.battlelobby. found o function from this project: [https://github.com/hotsdata/hots-parser](https://github.com/hotsdata/hots-parser) that returns player tags from that file and modified it to also be able to return the player levels. [Here](https://github.com/casualMLG/playerinfo_from_StormReplay/blob/master/pars.py) is my finished test code for getting these player related values. At line 33 is the part that gets the player level from the 4 bytes, in the function I was talking about. Now I can start making a python 2.7 program to generate a database from a bunch of replays or something.

**Comment by casualMLG** [comment]
One more thing...
trying to get replay date or datetime object.
the closest thing I found was m_timeUTC in replay.details. but its a long object that's too big to be a timestamp (i think). for example 'm_timeUTC': 131638102881283856L

**Comment by MGatner** [comment]
Check this out:
https://github.com/barrett777/Heroes.ReplayParser/blob/b05e8840d4086a558a9a55eb2f8f05135234544a/Heroes.ReplayParser/MPQFiles/ReplayDetails.cs

**Comment by casualMLG** [comment]
Thanks Matthew!
Didn't know about filetime. Got it converted now.

**Comment by Agilhardt** [comment]
#77 is fixed in the next update, as well mpyq will have been updated. Closing this thread.

**Comment by MGatner** [comment]
That’s great news! Is “next release” going to be with the next HotS patch?
