### ISSUE TITLE
Reading output from PHP

### ISSUE THREAD

**Issue by luchianenco** [Blizzard/heroprotocol#8]
I am running the heroprotocol from php application but the output data are not json compatible format
can you give me some hint how to use output data to get json format?

**Comment by Regner** [comment]
PR #3 adds JSON support. So you could look at that to get an idea of how to do that or wait to see if Blizzard responds to any of the PRs.

**Comment by surgun9** [comment]
python heroprotocol.py --json --details 222.StormReplay 
is not working

**Comment by surgun9** [comment]
changed json dump to UTF8 encoding
s = json.dumps(event, encoding="utf-8");
and I get next error

```
Traceback (most recent call last):
  File "heroprotocol.py", line 100, in <module>
    logger.log(sys.stdout, details)
  File "heroprotocol.py", line 44, in log
    s = json.dumps(event, encoding="utf-8");
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8d in position 11: invalid start byte
```
