### ISSUE TITLE
Not a bug but a qestion about the official GitHub account. as I didn’t found an other place to ask it.

### ISSUE THREAD

**Issue by ytrezq** [Blizzard/heroprotocol#82]
Are all Blizzard repositories even those from Blizzardgames in china supposed to be under this GitHub account?

Because I found https://www.wofgame.net/ which is about a game on Etherem (the cryptocurrency) which them claim is run by Blizzardgame. They even have a repository under https://github.com/blizzardgame (so not the same account).

Or is it a scam?

**Comment by Agilhardt** [comment]
That is not an official Blizzard GitHub account; the account is an imposter. I would not trust the code you get from it and would not download from the linked website.

Thank you for checking. Stay safe out there.

**Comment by ytrezq** [comment]
@Agilhardt : it’s not the account of Blizzard America/Worldwide, but because of Chinese laws, Blizzard china is a different company unlike elsewhere in the world. It might not have access to this GitHub account.
