### ISSUE TITLE
Unsupported base build: 81376

### ISSUE THREAD

**Issue by ScottIngram** [Blizzard/heroprotocol#93]
The replay file my HOTS just created chokes with the error message "Unsupported base build: 81376"

I looked in the 
https://github.com/Blizzard/heroprotocol/tree/master/heroprotocol/versions 
directory and it seems to only go up to 80702
https://github.com/Blizzard/heroprotocol/blob/master/heroprotocol/versions/protocol80702.py

**Comment by MGatner** [comment]
Same as #92

**Comment by ScottIngram** [comment]
fixed
