### ISSUE TITLE
Unsupported base build: 85267

### ISSUE THREAD

**Issue by Cruglk** [Blizzard/heroprotocol#96]
Same like: https://github.com/Blizzard/heroprotocol/issues/94 - but 85267.

And fix text on main page: https://github.com/Blizzard/heroprotocol

heroprotocol supports all **Hereos** of the Storm...

**Comment by Agilhardt** [comment]
Should be fixed now.

**Comment by Cruglk** [comment]
Thanks a lot, everything works now!
