### ISSUE TITLE
Unsupported base build: 88481

### ISSUE THREAD

**Issue by Elitesparkle** [Blizzard/heroprotocol#99]
Hello! The game version [2.55.3.88481](https://heroespatchnotes.com/patch/2022-07-12-hotfix-patch.html) isn't supported. Could you fix it, please?

**Comment by MGatner** [comment]
🥳

https://github.com/Blizzard/heroprotocol/releases/tag/v2.55.3.88481

**Comment by Elitesparkle** [comment]
Issue solved!
